version: 2
updates:
- package-ecosystem: npm
  directory: "/"
  schedule:
    interval: weekly
    time: "14:00"
  open-pull-requests-limit: 10
  ignore:
  - dependency-name: slug
    versions:
    - 4.0.2
    - 4.0.3
  - dependency-name: express-handlebars
    versions:
    - 5.2.0
    - 5.2.1
  - dependency-name: lodash
    versions:
    - 4.17.20
  - dependency-name: handlebars
    versions:
    - 4.7.6
